version: '3.4'

networks:
    backend:

services:
  infodb:
    container_name: info-db
    image: mcr.microsoft.com/mssql/server
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=vuhiep2k1072001
    networks:
        - backend
    ports:
        - 8005:1433

  tripdb:
    container_name: trip-db
    image: mcr.microsoft.com/mssql/server
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=vuhiep2k1072001
    networks:
        - backend
    ports:
        - 8006:1433

  chatdb:
    container_name: chat-db
    image: mcr.microsoft.com/mssql/server
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=vuhiep2k1072001
    networks:
        - backend
    ports:
        - 8007:1433

  infoservice:
    container_name: info-service
    image: ${DOCKER_REGISTRY-}infoservice
    build:
      context: .
      dockerfile: InfoService/Dockerfile
    networks:
        - backend
    environment:
        - DB_HOST=infodb
        - DB_NAME=dms_info
        - DB_SA_PASSWORD=vuhiep2k1072001

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
        - 8001:80
    networks:
        - backend

  authenticationservice:
    container_name: authentication-service
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    networks:
        - backend

  tripservice:
    container_name: trip-service
    image: ${DOCKER_REGISTRY-}tripservice
    build:
      context: .
      dockerfile: TripService/Dockerfile
    networks:
        - backend
    environment:
        - DB_HOST=tripdb
        - DB_NAME=dms_trip
        - DB_SA_PASSWORD=vuhiep2k1072001

  chatservice:
    container_name: chat-service
    image: ${DOCKER_REGISTRY-}chatservice
    build:
      context: .
      dockerfile: ChatService/Dockerfile
    networks:
        - backend
    environment:
        - DB_HOST=chatdb
        - DB_NAME=dms_chat
        - DB_SA_PASSWORD=vuhiep2k1072001

